//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAA.Models.DataBases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdCAAEntities : DbContext
    {
        public bdCAAEntities()
            : base("name=bdCAAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<caConcentraciones> caConcentraciones { get; set; }
        public DbSet<caConcentracionesProducto> caConcentracionesProducto { get; set; }
        public DbSet<caControl> caControl { get; set; }
        public DbSet<caDosis> caDosis { get; set; }
        public DbSet<caGruposQuimicos> caGruposQuimicos { get; set; }
        public DbSet<caIngredientesActivos> caIngredientesActivos { get; set; }
        public DbSet<caProductos> caProductos { get; set; }
        public DbSet<caTiposProductos> caTiposProductos { get; set; }
        public DbSet<caUnidadesMedida> caUnidadesMedida { get; set; }
    }
}
