//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAA.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class caIngredientesActivos
    {
        public caIngredientesActivos()
        {
            this.caProductos = new HashSet<caProductos>();
        }
    
        public int id { get; set; }
        public string IngredienteActivo { get; set; }
        public Nullable<int> idConcentracion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime fIns { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual caConcentraciones caConcentraciones { get; set; }
        public virtual ICollection<caProductos> caProductos { get; set; }
    }
}
