//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAA.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class caProductos
    {
        public int id { get; set; }
        public int idTipoProducto { get; set; }
        public string NombreComercial { get; set; }
        public Nullable<int> idIngredienteActivo { get; set; }
        public Nullable<int> idGrupoQuimico { get; set; }
        public Nullable<int> idDosis { get; set; }
        public Nullable<int> idConcentracionProducto { get; set; }
        public Nullable<int> idControl { get; set; }
        public System.DateTime fIns { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual caConcentracionesProducto caConcentracionesProducto { get; set; }
        public virtual caControl caControl { get; set; }
        public virtual caDosis caDosis { get; set; }
        public virtual caGruposQuimicos caGruposQuimicos { get; set; }
        public virtual caIngredientesActivos caIngredientesActivos { get; set; }
        public virtual caTiposProductos caTiposProductos { get; set; }
    }
}
