//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAA.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class caUnidadesMedida
    {
        public caUnidadesMedida()
        {
            this.caConcentraciones = new HashSet<caConcentraciones>();
            this.caConcentracionesProducto = new HashSet<caConcentracionesProducto>();
            this.caDosis = new HashSet<caDosis>();
        }
    
        public int id { get; set; }
        public string UnidadMedida { get; set; }
        public System.DateTime fIns { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual ICollection<caConcentraciones> caConcentraciones { get; set; }
        public virtual ICollection<caConcentracionesProducto> caConcentracionesProducto { get; set; }
        public virtual ICollection<caDosis> caDosis { get; set; }
    }
}
